stages:
  - build
  - deploy-stage-ansible
  - deploy-stage-helm
  - test-stage
  - deploy-prod-nginx
  - deploy-prod-helm

include:
  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-lint@10.2.4
    inputs:
      stage: build
      dir: ansible
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        changes:
          - ansible/**/*
      - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH  == $CI_DEFAULT_BRANCH
      - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH  == 'gesis'

  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-deploy@10.2.4
    inputs:
      stage: deploy-stage-ansible
      dir: ansible
      inventory: gesis-stage
      playbook: gesis.yml
      ssh-user: ansible
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        changes:
          - ansible/**/*
      - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH  == $CI_DEFAULT_BRANCH
      - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH  == 'gesis'