stages:
  - build
  - deploy-stage-ansible
  - deploy-stage-helm
  - test-stage
  - deploy-prod-nginx
  - deploy-prod-helm

include:
  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-lint@10.2.6
    inputs:
      stage: build
      dir: ansible

  - component: $CI_SERVER_FQDN/rse/docker/images/ansible/ansible-deploy@10.2.6
    inputs:
      stage: deploy-stage-ansible
      dir: ansible
      inventory: gesis-stage
      playbook: gesis.yml
      ssh-user: ansible

smoke test to stage cluster:
  stage: test-stage
  script:
    - curl https://notebooks-test.gesis.org/binder/