- name: Add a Ingress NGINX Controller Helm repository
  kubernetes.core.helm_repository:
    repo_name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    force_update: true
- name: Create Ingress NGINX Controller Kubernetes namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ingress-nginx
- name: Deploy Ingress NGINX Controller
  kubernetes.core.helm:
    release_name: ingress-nginx
    release_namespace: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: '{{ k8s_control_panel_ingress_nginx_version }}'
    create_namespace: false
    history_max: 3
