- name: Configure servers that are part of Kubernetes cluster
  hosts: all
  gather_facts: false
  become: true
  roles:
    - k8s-common
- name: Configure Kubernetes control panel
  hosts: kubernetes_control_panel
  gather_facts: false
  become: true
  roles:
    - k8s-control-panel
- name: Configure Kubernetes workers
  hosts: kubernetes_workers
  gather_facts: false
  become: true
  roles:
    - k8s-worker
- name: Configure Kubernetes Persistent Volumes
  hosts: kubernetes_control_panel
  gather_facts: false
  become: true
  roles:
    - k8s-pv
- name: Configure JupyterHub workers
  hosts: jupyterhub_single_user
  gather_facts: false
  become: true
  roles:
    - k8s-worker
- name: Configure mybinder.org Kubernetes cluster
  hosts: kubernetes_control_panel
  gather_facts: false
  roles:
    - mybinder
