- name: Configure servers that are part of Kubernetes cluster
  hosts: all
  gather_facts: false
  become: true
  roles:
    - k8s-common
- name: Configure Kubernetes control panel
  hosts: kubernetes_control_panel
  gather_facts: false
  become: true
  roles:
    - k8s-control-panel
