- name: Create directory /etc/apt/keyrings if it does not exist
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings
- name: Remove old Kubernetes public GPG key
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
    state: absent
- name: Remove old Kubernetes public GPG key
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.asc
    state: absent
- name: Remove old Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes
    state: absent
- name: Remove old Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /"
    filename: kubernetes
    state: absent
- name: Ensure DOCKER_CLIENT_TIMEOUT is set
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^DOCKER_CLIENT_TIMEOUT='
    line: DOCKER_CLIENT_TIMEOUT=180
- name: Disable SWAP since kubernetes can't work with swap enabled
  ansible.builtin.shell: swapoff -a
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
- name: Disable Firewall
  ansible.builtin.shell: ufw disable
- name: Allow IP forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
- ansible.posix.sysctl:
    name: fs.inotify.max_user_instances
    value: '1280'
    state: present
- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '655360'
    state: present
- name: Create /orc2_data/containerd directory if it does not exist
  ansible.builtin.file:
    path: /orc2_data/containerd
    state: directory
- name: Create /orc2_data/repo2docker directory if it does not exist
  ansible.builtin.file:
    path: /orc2_data/repo2docker
    state: directory
- name: Create /orc2_data/prometheus directory if it does not exist
  ansible.builtin.file:
    path: /orc2_data/prometheus
    state: directory
- name: Create /orc2_data/grafana directory if it does not exist
  ansible.builtin.file:
    path: /orc2_data/grafana
    state: directory
- name: Create /orc2_data/alertmanager directory if it does not exist
  ansible.builtin.file:
    path: /orc2_data/alertmanager
    state: directory
- name: Create /harbor/jobservice directory if it does not exist
  ansible.builtin.file:
    path: /harbor/jobservice
    state: directory
- name: Create /harbor/registry directory if it does not exist
  ansible.builtin.file:
    path: /harbor/registry
    state: directory
- name: Create /harbor/redis directory if it does not exist
  ansible.builtin.file:
    path: /harbor/redis
    state: directory
- name: Create /harbor/trivy directory if it does not exist
  ansible.builtin.file:
    path: /harbor/trivy
    state: directory
- name: Create /harbor/database directory if it does not exist
  ansible.builtin.file:
    path: /harbor/database
    state: directory
- name: Add Docker public GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
    filename: docker
    state: present
- name: Download Kubernetes public GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key
    dest: /tmp/kubernetes-archive-keyring.asc
    mode: '0644'
    force: true
- name: Convert the public GPG key to binary
  ansible.builtin.command:
    argv:
      - gpg
      - --yes
      - --dearmor
      - --output
      - /tmp/kubernetes.gpg
      - /tmp/kubernetes-archive-keyring.asc
- name: Copy GPG key
  ansible.builtin.copy:
    src: /tmp/kubernetes.gpg
    dest: /etc/apt/keyrings/kubernetes.gpg
    remote_src: true
    mode: '0644'
- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /"
    filename: kubernetes
    state: present
- name: Add Helm public GPG key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/trusted.gpg.d/helm.asc
    mode: '0644'
    force: true
- name: Add Helm repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
    filename: kubernetes
    state: present
- name: Install dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - rsync
      - python3
      - apt-transport-https
      - ca-certificates
      - curl
      - containerd.io=1.7.*
      - kubelet=1.28.*
      - kubeadm=1.28.*
      - kubectl=1.28.*
      - helm=3.15.*
- name: Copy containerd configuration file
  ansible.builtin.copy:
    src: files/etc/containerd/config.toml
    dest: /etc/containerd/config.toml
- name: Reload service containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
- name: Enable service containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    masked: false